spring:
  application:
    name: route_service

  datasource:
    url: jdbc:postgresql://localhost:5432/route_service_db
    username: tework
    password: ksflkOkas23fl9saflKdl349sLfsk1
    hikari:
      auto-commit: false
    jpa:
      hibernate:
        ddl-auto: validate
      show-sql: false
      # properties:
      #   hibernate:
      #     generate_statistics: true
    liquibase:
      enabled: true

#logging:
#  level:
#    org:
#      hibernate:
#        SQL:
#        type: TRACE
#    springframework:
#      security: DEBUG
#    root: INFO
#    com:
#      example: DEBUG
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n" # Формат вывода в консоль
#  file:
#    name: logs/myapp.log
#    max-size: 10MB
#    max-history: 30