server:
  port: 9000

spring:
  application:
    name: route_service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      auto-commit: false

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    properties:
      hibernate.format_sql: true

  liquibase:
    enabled: true

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000


openrouteservice:
  api-key: ${OPENROUTESERVICE_API_KEY}

openweathermap:
  api-key: ${openrouteservice_API_KEY}
