spring:
  application:
    name: route_service

  datasource:
    url: jdbc:postgresql://localhost:5432/route_service_db
    username: tework
    password: ksflkOkas23fl9saflKdl349sLfsk1
    hikari:
      auto-commit: false
    jpa:
      hibernate:
        ddl-auto: validate
      show-sql: true
      properties:
        hibernate.format_sql: true

    liquibase:
      enabled: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

openrouteservice:
  api-key: 5b3ce3597851110001cf62483f26b17e6a754540adf28bc137fa9fed
openweathermap:
  api-key: aa0a32f4341403aa09700231c23386ce