services:
  postgres:
    image: postgis/postgis:17-3.5
    container_name: route_service_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5999:5432"
    volumes:
      - ./route_service.sql:/docker-entrypoint-initdb.d/dump.sql
      - ./init-postgis.sql:/docker-entrypoint-initdb.d/init-postgis.sql
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # AMQP порт
      - "15672:15672"   # Web UI (RabbitMQ Management)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    restart: unless-stopped