services:
  postgres:
    image: postgis/postgis:17-3.5
    container_name: route_service_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - ./route_service.sql:/docker-entrypoint-initdb.d/dump.sql
      - ./init-postgis.sql:/docker-entrypoint-initdb.d/init-postgis.sql
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    restart: unless-stopped